### PR TITLE
Add shortcuts for creating fulfilled / rejected promises

### PR DESCRIPTION
**Pull request by franzliedke**
When you want to create an already fulfilled (or rejected) promise, this lets you do `Restify::Promise.fulfilled(42)`. :)

### CODE REVIEW

**Comment by franzliedke** [comment]
Plus, extending from `IVar` could be considered an implementation detail.

**Comment by jgraichen** [comment]
The `IVar` should have `#then` too.

**Comment by franzliedke** [comment]
For promise dependencies, we only need `value!`, I believe.

**Comment by jgraichen** [comment]
Yes. What I meant was something like this `Promise::fulfilled(0).then |null| ..`. That wouldn't be possible with `IVar`.

**Comment by franzliedke** [comment]
I would love to add some examples with real asynchronicity, but did not want to use `sleep`. Threads?

**Comment by franzliedke** [comment]
Hmm, looks like there are shortcuts for all of these with `IVar`: https://github.com/ruby-concurrency/concurrent-ruby/blob/aa2b81125b05d86ec601710d1ac766ca40191a3e/spec/concurrent/ivar_spec.rb#L14-L29

**Comment by franzliedke** [comment]
Added an example with asynchronous code.

**Pull request merged**
